// <auto-generated />
using InspectionRequestAPI.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InspectionRequestAPI.Migrations
{
    [DbContext(typeof(InspectionRequestDbContext))]
    [Migration("20240229155044_Adding tables")]
    partial class Addingtables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");
#pragma warning restore 612, 618
        }
    }
}
